### ISSUE TITLE
event.fields undefined on safari

### ISSUE THREAD

**Issue by quewon** [Ragzouken/bipsi#1]
in a red box right before every event (including the title box) that fires:

```
SCRIPT ERROR:
TypeError: undefined is not an object (evaluating 'event.fields')
```

otherwise, everything else seems to work fine.

**Comment by quewon** [comment]
upd8 : looks like it happens on chrome too? weird, maybe it's my device? (2020 mac m1)

```
SCRIPT ERROR:
TypeError: Cannot read properties of undefined (reading 'fields')
```

**Comment by Ragzouken** [comment]
pretty sure i've fixed this now, let me know if you still have the issue. thank you
